Repository whtjdqls617/ios-wanted-CustomKeyboard, pull requests merged in 2022-07, with the labels that each got.

#4 [#2] 키보드 UI 구현 및 reviewList 버튼 타입 변경
  CustomKeyboard.xcodeproj/project.pbxproj
  CustomKeyboard/Presentation/Keyboard/Cell/KeyboadCollectionViewCell.swift
  CustomKeyboard/Presentation/Keyboard/View/KeyboardView.swift
  CustomKeyboard/Presentation/Keyboard/View/KeyboardViewController.swift
  CustomKeyboard/Presentation/ReviewList/Cell/ReviewListTableViewCell.swift
  CustomKeyboard/Presentation/ReviewList/View/ReviewListView.swift
  CustomKeyboard/Presentation/ReviewList/View/ReviewListViewController.swift
Labels: 국, Style, Fix

#12 [Feat] 오토마타, button 연결 및 post 구현 완료
  CustomKeyboard.xcodeproj/project.pbxproj
  CustomKeyboard/Presentation/Keyboard/View/KeyboardView.swift
  CustomKeyboard/Presentation/Keyboard/View/KeyboardViewController.swift
  CustomKeyboard/Presentation/ReviewList/View/ReviewListView.swift
  CustomKeyboard/Presentation/ReviewList/View/ReviewListViewController.swift
  CustomKeyboard/Resource/Base.lproj/LaunchScreen.storyboard
  unicode_test.playground/Contents.swift
  unicode_test.playground/contents.xcplayground
Labels: Feat

#14 [Fix] Label 내용이 길어졌을 때 버튼 사라지는 버그 수정
  CustomKeyboard/Presentation/ReviewList/View/ReviewListView.swift
Labels: Fix

#26 [Feat] Post성공시 table Cell 추가 구현
  CustomKeyboard/Presentation/ReviewList/View/ReviewListViewController.swift
  CustomKeyboard/Presentation/ReviewList/ViewModel/ReviewListViewModel.swift
  ReviewData.swift
  ReviewDataManager.swift
Labels: Feat
